name: pretty_good_spacing
description: "A configurable spacing system for Flutter applications with consistent design tokens and convenient widgets."
version: 0.0.1
homepage: https://github.com/DanhTran0312/pretty_good_spacing
repository: https://github.com/DanhTran0312/pretty_good_spacing

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

